## Basics 2

<div class="alert alert-info">
<b>Exercise 7</b><br>
a) Write a function that separates odd and even numbers.<br>
b) Write a function that returns the list of ages above a certain threshold.
</div>

In [1]:
lst = [2,3,4,5,6,7,8]
def sepOdds1(lstOfNumbers):
    return [num for num in lstOfNumbers if num % 2 == 0],[num for num in lstOfNumbers if num % 2 == 1]

In [2]:
def sepOdds2(lstOfNumbers):
    even = []
    odd = []
    for i in lstOfNumbers:
        if i % 2 == 0:
            even.append(i)
        elif i % 2 == 1:
            odd.append(i)
    return even, odd

In [3]:
sepOdds1(lst) == sepOdds2(lst)

True

In [4]:
ages = [18,19,20,21,17,14,15,22,44,55,66,77,2]

In [5]:
def thresholdAge1(lstOfAges,threshold):
    result = []
    for age in lstOfAges:
        if age > threshold:
            result.append(age)
    return result

In [6]:
def thresholdAge2(lstOfAges,threshold):
    return [age for age in lstOfAges if age > threshold]

In [7]:
thresholdAge1(ages,22)

[44, 55, 66, 77]

In [8]:
thresholdAge2(ages,22)

[44, 55, 66, 77]

<div class="alert alert-info">
Return Xth element from:<br>
a) the given string `s`. X = third. Solution: i<br>
b) the given list `lst`. X = fifth. Solution: 3
</div>

In [9]:
s = "Heinrich Heine University"

In [10]:
lst = [0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597,2584,4181,6765]

In [11]:
s[2]

'i'

In [12]:
lst[4]

3

<div class="alert alert-info">
Return Xth-Yth elements from:<br>
a) the given string `s`. X-Y = start - 15th. Solution: Heinrich Heine<br>
b) the given list `lst`. X-Y = 10th - 17th. Solution: [55, 89, 144, 233, 377, 610, 987, 1597]
</div>

In [13]:
s

'Heinrich Heine University'

In [14]:
s[0:14]

'Heinrich Heine'

In [15]:
lst[10:18]

[55, 89, 144, 233, 377, 610, 987, 1597]

<div class="alert alert-info">
Return every second element from the given list `lst`. Solution: [0, 1, 3, 8, 21, 55, 144, 377, 987, 2584, 6765]
</div>

In [16]:
lst[::2]

[0, 1, 3, 8, 21, 55, 144, 377, 987, 2584, 6765]

<div class="alert alert-info">
Safe the substring Heine under the variable name `var` by slicing the string `s`.
</div>

In [17]:
s

'Heinrich Heine University'

In [18]:
var = s[9:14]

In [19]:
var

'Heine'

<div class="alert alert-info">
Transform `var` to only uppercase letters.
</div>

In [20]:
varUppercase = var.upper()

In [21]:
var

'Heine'

In [22]:
varUppercase

'HEINE'

In [23]:
lst.reverse()

In [24]:
help(list.reverse)

Help on method_descriptor:

reverse(self, /)
    Reverse *IN PLACE*.



In [25]:
help(str.upper)

Help on method_descriptor:

upper(self, /)
    Return a copy of the string converted to uppercase.



<div class="alert alert-info">
a) Extract the month from the given date `date`, transform it into a number and safe it under the variable name `month`.<br>
b) Use two different approaches.
</div>

In [26]:
date = "2017-03-29"

In [27]:
date.split("-")

['2017', '03', '29']

In [28]:
month = int(date.split("-")[1])

In [29]:
month

3

In [30]:
import datetime

In [31]:
datetime.date(2017,3,29)

datetime.date(2017, 3, 29)

In [32]:
date_time_str = '2018-06-29 08:15:27.243860'
date_time_obj = datetime.datetime.strptime(date_time_str, '%Y-%m-%d %H:%M:%S.%f')

In [33]:
date_time_obj

datetime.datetime(2018, 6, 29, 8, 15, 27, 243860)

<div class="alert alert-info">
What are the results for the following code given (<i>Don't run the code</i>):<br>
a) x = 3<br>
b) x = 10<br>
c) y = 2 and x = 2<br>
d) z = 5<br>
</div>

a) "Adenin"
b) "Guanin"
c) "Cytosin"
d) "Cytosin"

# Markdown Cell

*Markdown*
$a^{2}$

<div class="alert alert-info">
Choose values for x, y, z for the code above such that "Uracil" will be printed.
</div>

In [35]:
def test(x=1,y=1,z=1):
    if x%3==0:
        print("Adenin")
    elif x > 4:
        if x == y:
            print("Uracil")
        else:
            print("Guanin")
    elif x < 3:
        print("Cytosin")
    else:
        print("Thymin")

In [36]:
test(5,5,1)

Uracil


In [37]:
test(15,15,1)

Adenin
